version: '3.8'

services:
  # Redis Standalone
  redis-standalone:
    image: redis:7.2
    container_name: redis-standalone
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - redis-cluster

  # Redis Cluster Nodes
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    hostname: redis-node-1
    ports:
      - "7000:7000"
    command: ["redis-server", "--port", "7000", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    hostname: redis-node-2
    ports:
      - "7001:7001"
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    hostname: redis-node-3
    ports:
      - "7002:7002"
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      - redis-cluster

  redis-cluster-init:
    image: redis:7.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: >
      bash -c "
      sleep 5 &&
      echo 'yes' | redis-cli --cluster create \
        redis-node-1:7000 \
        redis-node-2:7001 \
        redis-node-3:7002 \
        --cluster-replicas 0"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
